### PR TITLE
Change get_url(cachebust=true) to use a hash

### LINKED ISSUE #519: Asset fingerprinting and SRI
It'd be nice if there were a way of accessing a fingerprint or hash of static files, for a more reliable way of caching assets. 

I've given this a bit of thought, and probably need some input.

Ideally, it'd just be an additional function, say `get_static`, which returned a structure which contained the path, fingerprinted URL, hash, things like that. Because this requires the static files to exist before running, it would also serve as a link checker. However, What do we do about live reloading? When editing a static file, we'd either need to keep track of the linked resources per page, and only reload the linked pages, or just reload the whole site. (The latter is _so_ much easier!)

I see no reason why this couldnt work for any static file in the site, eg images. It wouldnt play well with images after they've been processed, but static images should work fine!

### PR DESCRIPTION
**Pull request by dancek**
Cache-busting was previously done with a compile-time timestamp. Change
to the SHA-256 hash of the file to avoid refreshing unchanged files.

The implementation could be used to add a new global fn (say,
get_file_hash) for subresource integrity use, but that's for another
commit.

Fixes #519.

**IMPORTANT: Please do not create a Pull Request adding a new feature without discussing it first.**

The place to discuss new features is the forum: <https://zola.discourse.group/>
If you want to add a new feature, please open a thread there first in the feature requests section.

Sanity check:

* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/getzola/zola/pulls) for the same update/change?

## Code changes
(Delete or ignore this section for documentation changes)

* [x] Are you doing the PR on the `next` branch?

If the change is a new feature or adding to/changing an existing one:

* [x] Have you created/updated the relevant documentation page(s)?

### CODE REVIEW

**Comment by dancek** [comment]
I'm not very seasoned with Rust, so I'll appreciate any review comments. Especially the `TestContext` part seems a bit questionable to me, but this way I *think* the directory should get cleaned up even when a test panics.

**Comment by dancek** [comment]
```
error: failed to run custom build command for `onig_sys v69.2.0`
```
I don't think this is caused by my changes. 🤔

**Comment by Keats** [comment]
Don't worry about that, it's being fixed upstream.

**Comment by Keats** [comment]
Thanks!

**Pull request merged**
