### PR TITLE
Add 'this' var to alias page or section for templates

### PR DESCRIPTION
**Pull request by Raymi306**
**IMPORTANT: Please do not create a Pull Request adding a new feature without discussing it first.**

The place to discuss new features is the forum: <https://zola.discourse.group/>
If you want to add a new feature, please open a thread there first in the feature requests section.

Sanity check:

* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/getzola/zola/pulls) for the same update/change?

## Code changes
(Delete or ignore this section for documentation changes)

* [x] Are you doing the PR on the `next` branch?

If the change is a new feature or adding to/changing an existing one:

* [ ] Have you created/updated the relevant documentation page(s)?
---
Fixes issue #687

If there is interest in this PR I can edit the documentation.

Also, this was only a few lines to implement, definitely let me know if I missed something or oversimplified this.

### CODE REVIEW

**Comment by Keats** [comment]
That's something we want to do but not right now, it would make the current rendering quite slow. In the next Tera version we should be able to that without perf impact

**Comment by Raymi306** [comment]
Closing, waiting for next Tera version

**Comment by aterenin** [comment]
Gentle ping on this: has the Tera version been updated so that this is no longer a problem? Having a variable called `this` so that I don't have to add `{% set this = page | default(value = section) %}` to a bunch of template files would be extremely useful.

**Comment by Keats** [comment]
It's not done yet: https://github.com/Keats/tera2

Next is making it so tests/filters/fns can access the values in the current scope so you don't need to do things like `lang=lang`

**Comment by salif** [comment]
How to do this in tera2?

**Comment by Keats** [comment]
That will be part of a bigger discussion: https://zola.discourse.group/t/section-vs-page/522
I'll start a RFC soonish

**Pull request closed without merging**
