### PR TITLE
Don't scale images up when resizing with fit

### PR DESCRIPTION
**Pull request by Nukesor**
These are the changes as discussed in the following forum thread: https://zola.discourse.group/t/new-image-resizing-mode-shrink-fit/203

Documentation changes have been made and tested.

### CODE REVIEW

**Comment by Keats** [comment]
cc @vojtechkral what do you think?  It makes sense to me

**Comment by vojtechkral** [comment]
Cool, I'll have a look either tonight or tomorrow...

**Comment by vojtechkral** [comment]
Generally, this looks good to me.

My original purpose was picture/photo galleries where the previous behaviour _might in theory_ make sense to make the thumbnails uniform... However, (1) this can be solved on the frontend with css/js, and (2) people are pretty unlikely to have pictures in galleries smaller then the thumbnail, so, this is probably moot.

Anyway, it's fine by me. I just hope the change doesn't break anyone's workflow, but I find it unlikely.

Thanks!

**Comment by Keats** [comment]
Yeah I think it makes sense to me to not upscale since this is never really what you want. We'll see if it breaks for someone and if so we can add a shrink_fit and revert the changes to fit.

Thanks, both of you!

**Pull request merged**
