### PR TITLE
Send Appropriate Response on Error

### PR DESCRIPTION
**Pull request by m-laniakea**
Users can now place custom error pages in static/error/<error_code>.html
e.g. static/error/404.html

If no custom page is found, a default plaintext describing the error is served.

### CODE REVIEW

**Comment by Keats** [comment]
I think the file looked up should be `templates/404.html` but that means we need to ensure it's going to be generated, like the sitemaps etc

**Comment by m-laniakea** [comment]
Would you prefer `templates/<error_code>.html` or `templates/error/<error_code>.html`?

So you want Gutenberg to check for error templates and generate them, is that right?

**Comment by Keats** [comment]
Yes, so nginx/netlify etc can display the 404 if there is one. I'd prefer `templates/404.html`, I don't think there are other error codes to be added afaik.
Also if you can change the branch to do the PR on the `next` branch that would be great!

**Comment by Serkan-devel** [comment]
Maybe something like 503.html ?

**Comment by Keats** [comment]
would 503 be used for static sites?

**Comment by Keats** [comment]
Note that I merged a PR to move from iron to actix-web as iron is unmaintained so this PR would need to be rewritten. I still want it in though

**Comment by onelson** [comment]
Peeking at the actix-web middleware [intro](https://actix.rs/docs/middleware/), seems like the implementation would be virtually identical. Mostly the work would be to switch out the types for their actix counterparts.

As an aside, I host my gutenberg site on s3, and I only remember the option to provide a single generic "error" document. Wonder if we could emulate both behaviours by checking for a status code file, then falling back to check for a generic error file.

**Comment by Keats** [comment]
Anyone wants to pick this up?

**Comment by onelson** [comment]
I can probably take a look over the weekend if someone else doesn't get to it first.

**Comment by onelson** [comment]
I have something compiling now, but need to test and polish. Not sure how best to handle the hand-off for the PR. Close and open a new one?

**Comment by Keats** [comment]
Yes, i'll close this one as I don't think any part of the code can be re-used

**Pull request closed without merging**
