### PR TITLE
Add page templates to sections

### PR DESCRIPTION
**Pull request by IvoWingelaar**
Following this #397, it appears this issue is quite more involved then I initially suspected. It appears that applying a `page_template` recursively is a worthwhile addition, but to keep this PR minimal this is **not** currently done.

### CODE REVIEW

**Comment by Keats** [comment]
Can you add it to the documentation as well?

**Comment by Keats** [comment]
ping @IvoWingelaar 
Was there any issue with the recursiveness? I don't mind having the PR be a bit bigger

**Comment by IvoWingelaar** [comment]
> Can you add it to the documentation as well?

Yeah, of course I can add it to the documentation! I had some real-life obligations that interfered.

> Was there any issue with the recursiveness? 

None that are show stopping. The obvious place to add the recursion fails some tests for reasons that I currently do not understand. But to be fair, I didn't had the chance to properly debug yet.

**Comment by IvoWingelaar** [comment]
> The obvious place to add the recursion fails some tests for reasons that I currently do not understand.

In `site::Site` we store a `sections: HashMap` that owns the `Sections`. That's why we need to make clones of them when we populate `content::Section::subsections`. This necessitates two passes over all sections to apply the themes correctly: the first one to link the section to all its pages, and a second one to apply the themes.

**Comment by Keats** [comment]
I have a pretty huge refactor locally that removes all the cloning. It's not ready yet but should be soonish so probably worth waiting a bit

**Comment by IvoWingelaar** [comment]
Ah, then I'll just prepare the documentation, and wait for the refactoring.

**Comment by Keats** [comment]
The refactoring has been merged

**Comment by Keats** [comment]
@IvoWingelaar are you planning to finish the PR or should I do it?

**Comment by Keats** [comment]
@IvoWingelaar ping

**Comment by Keats** [comment]
I have pushed an updated version that works recursively in the `next` branch so closing this

**Pull request closed without merging**
