### PR TITLE
Add --open flag to serve command, to open URL in default browser

### PR DESCRIPTION
**Pull request by timvisee**
> **IMPORTANT: Please do not create a Pull Request adding a new feature without discussing it first.**
>
> The place to discuss new features is the forum: <https://zola.discourse.group/>
> If you want to add a new feature, please open a thread there first in the feature requests section.

I noticed this message after adding this feature. Since it's quite small I decided to initiate the PR anyway. Please tell me if a discussion for this is still desired. In that case I'll be sure to follow up to that.

This PR adds an `--open` flag to the `serve` command, to open the URL the page is locally hosted at in the default browser of the user. While working with `zola` I commonly wanted to have such functionality  built-in, thus I decided to add this.

---

Sanity check:

* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/getzola/zola/pulls) for the same update/change?

## Code changes
(Delete or ignore this section for documentation changes)

* [x] Are you doing the PR on the `next` branch?

If the change is a new feature or adding to/changing an existing one:

* [x] Have you created/updated the relevant documentation page(s)?

### CODE REVIEW

**Comment by zimmi** [comment]
Just a casual observation: Maybe opening the browser should be the default when running `zola serve` and there should be something like a `--no-open` flag (if at all)?

**Comment by timvisee** [comment]
> Just a casual observation: Maybe opening the browser should be the default when running `zola serve` and there should be something like a `--no-open` flag (if at all)?

I can imagine that to become annoying, even though it's a simple flag. I've had various cases where I had to re-invoke the command constantly due to theme, config or taxonomy changes. Just my thought of course.

**Comment by awulkan** [comment]
I'd rather not have the website be opened by default. But I would like to have it as an optional flag.

**Comment by Keats** [comment]
Looks good, thanks!
This definitely needs to be opt-in.

**Comment by zimmi** [comment]
> I can imagine that to become annoying, even though it's a simple flag. I've had various cases where I had to re-invoke the command constantly due to theme, config or taxonomy changes. Just my thought of course.

Yeah, makes sense!

**Pull request merged**
