### PR TITLE
fix clojure syntax highlighting

### PR DESCRIPTION
**Pull request by vise890**
Fix clojure syntax highlighting as per #1268,

 also [sublime-clojure provides better highlighting in some corner-cases](https://github.com/tonsky/sublime-clojure)

I tried to follow the procedure in the contrib guidelines, but feel free to close or ask for edits if something is not right! :smile:

### CODE REVIEW

**Comment by Keats** [comment]
I'm not sure it will work well, syntect will load the whole folder but I don't know if the order will be deterministic

**Comment by vise890** [comment]
I see, it's probably worth closing this until we find a proper way to deal with it then? Is it worth opening an issue with syntect then since it is likely to be affected too?

**Comment by Keats** [comment]
Not worth a syntect issue, we just need to have a better way to override the syntaxes in zola. I'll check next week, it shouldn't be too hard.

**Comment by vise890** [comment]
Ok great, thank you for looking into it! :smile:

**Pull request closed without merging**
