### PR TITLE
Next

### PR DESCRIPTION
**Pull request by Keats**

### CODE REVIEW

**Comment by eberkund** [comment]
Is there anything blocking this from release? I would absolutely love to be able to use colocated subfolders :)

**Comment by Keats** [comment]
Nothing blocking, just waiting for the release to be a bit more meaty

**Comment by eberkund** [comment]
> Nothing blocking, just waiting for the release to be a bit more meaty

Is it possible to make a release anyways? Colocated subfolders are a very nice feature to have IMO and a release where that is the only addition would be fantastic.

**Comment by Keats** [comment]
I want to get at least https://github.com/getzola/zola/pull/1640 in before releasing. It's getting there (locally), it's probably going to get merged by the end of the week unless some unexpected issues appear.
Once it's merged, there will be a new release soon after.

**Comment by eberkund** [comment]
> I want to get at least #1640 in before releasing. It's getting there (locally), it's probably going to get merged by the end of the week unless some unexpected issues appear. Once it's merged, there will be a new release soon after.

Awesome, looking forward to it!

**Comment by scouten** [comment]
@eberkund FYI if you are using Netlify to deploy your site and you want to deploy using something that hasn't been released yet, I found myself in a similar situation a few months ago. This might be helpful: https://ericscouten.dev/2021/custom-zola-build/

**Comment by Keats** [comment]
Any thoughts on https://github.com/getzola/zola/pull/1640#issuecomment-974369707 and the comment below?

**Comment by Keats** [comment]
Ok, just looking to get one fix for https://github.com/getzola/zola/pull/1672 in and then it should get released this weekend.

Can anyone reading this and using shortcodes try this branch? It has been completely rewritten so it would be nice to detect potential issues before releasing.

And for people that cares about colocating sections, also have a look at https://github.com/getzola/zola/pull/1672

**Comment by acheronfail** [comment]
@Keats I've run it on my repository which has ~10 custom shortcodes, and everything seems to be just fine on my end. I can't see anything out of the ordinary, and it all seems to work. :+1:

**Comment by eberkund** [comment]
@Keats I tried the sub-folder colocation with #1672 and it still works as expected.

**Comment by Keats** [comment]
Great to hear!

**Pull request merged**
