### PR TITLE
Implemented emoji aliases support in markdown files

### LINKED ISSUE #292: [feature request] emojis
Hugo provides [this feature](https://gohugo.io/functions/emojify/). I know development time could be spent on more important features. But, since the markdown renderer going through a re-write and implementing this feature might not be that hard, it would be great to see it in Gutenberg in the near future.

Thanks!

### PR DESCRIPTION
**Pull request by pacmancoder**
## Code changes
- Implemented emoji aliases substitution based on gh-emoji crate
- Added config option to control emoji substitution logic (_emoji_rendering_ bool value)
- Update documentation page with the emoji_rendering option description

Fixes #292

### CODE REVIEW

**Comment by Keats** [comment]
Can you add a benchmark to check the speed difference between a text with and without emoji enabled?

**Comment by pacmancoder** [comment]
@Keats I have added _bench_render_content_no_shortcode_with_emoji_ bench.
Here are the results:
```
test bench_render_content_no_shortcode            ... bench:      21,161 ns/iter (+/- 3,513)
test bench_render_content_no_shortcode_with_emoji ... bench:      31,736 ns/iter (+/- 1,893)
test bench_render_content_with_highlighting       ... bench:     117,083 ns/iter (+/- 2,703)
test bench_render_content_without_highlighting    ... bench:     116,673 ns/iter (+/- 4,076)
test bench_render_shortcodes_one_present          ... bench:      91,217 ns/iter (+/- 1,634)
```

**Comment by pacmancoder** [comment]
@Keats any updates on this PR? will it land in the next version, or some kind of rework is required for the merge?

**Comment by Keats** [comment]
Sorry, forgot about that!

**Pull request merged**
