### PR TITLE
Quotation mark bug fix in docs

### PR DESCRIPTION
**Pull request by YesSeri**
Changed double quotation mark " to single quotation ', otherwise the code doesn't work.

Sanity check:

* [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/getzola/zola/pulls) for the same update/change?

### CODE REVIEW

**Comment by Keats** [comment]
Why would double quotes not work? I'm only using them everywhere

**Comment by YesSeri** [comment]
I should have been more clear in my communication.

```
"{{/* get_url(path="@/blog/_index.md") */}}"
```

You have nested quotation marks here. That means that the  code above gets interpreted as 

```html
// Text
"{{/* get_url(path="
//Html
@/blog/_index.md
// Text
") */}}"
```

Does my example make sense? 

I think it is only a problem here, but if you accept my pull request I can look through all of the documentation for similar problems.

What do you think?

**Comment by Keats** [comment]
Why would you have newlines in there?

**Comment by YesSeri** [comment]
There should not be newlines. I was just trying to emphasize my point. Do you understand why the code doesn't work?

**Comment by Keats** [comment]
I don't sorry, I must be dense 😿

**Comment by jtojnar** [comment]
Perhaps @YesSeri means syntax highlighting is broken in some editors?

**Comment by jtojnar** [comment]
Actually, it even breaks syntax highlighting on the website:

Bottom of the Overview page

**Review by Keats — APPROVED** [review]

**Comment by YesSeri** [comment]
> Actually, it even breaks syntax highlighting on the website:
> 
> Bottom of the Overview page

Well, the syntax highlightning is broken because the code is broken. If you want to nest double quotation marks you need a way to escape them or you can use single quotation marks.

**Pull request merged**
