### PR TITLE
Add final directory structure to overview

### PR DESCRIPTION
**Pull request by bbkane**
For https://github.com/getzola/zola/issues/1341

**IMPORTANT: Please do not create a Pull Request adding a new feature without discussing it first.**

The place to discuss new features is the forum: <https://zola.discourse.group/>
If you want to add a new feature, please open a thread there first in the feature requests section.

Sanity check:

* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/getzola/zola/pulls) for the same update/change?

## Code changes
(Delete or ignore this section for documentation changes)

* [ ] Are you doing the PR on the `next` branch?

If the change is a new feature or adding to/changing an existing one:

* [ ] Have you created/updated the relevant documentation page(s)?

### CODE REVIEW

**Review by Keats — APPROVED** [review]

**Comment by Keats** [comment]
Thanks!

**Comment by rootkea** [comment]
Why wasn't this PR be merged in `next` branch?

Also file `second.md` is missing in this PR. Should I cherrypick this commit and add another commit adding `second.md` and send PR on `next` branch?

Or should I add a single commit (this commit + adding `second.md` file) and send PR on `next`?

**Comment by Keats** [comment]
Documentation changes can go straight to master and will be merged back in the `next` branch before merging it

**Comment by rootkea** [comment]
Thanks! Just sent #1469 :)

**Pull request merged**
