### PR TITLE
Add new sorting: UpdateDate that sorts by `meta.updated`.

### LINKED ISSUE #1384: Feature Request: sort section by "updated"
Hello,

https://www.getzola.org/documentation/content/section/#sorting describes how to sort by "date" within a section. pages also have an "[updated](https://www.getzola.org/documentation/content/page/#front-matter)" variable in the front matter that I'd like to sort my section by. Would it be difficult to add that as an option?

### PR DESCRIPTION
**Pull request by WaffleLapkin**
This resolves #1384.

I don't know where to add tests/update documentation (it's my first time contributing to zola) so I didn't.

-----

Sanity check:

* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/getzola/zola/pulls) for the same update/change?

## Code changes
(Delete or ignore this section for documentation changes)

* [x] Are you doing the PR on the `next` branch?

If the change is a new feature or adding to/changing an existing one:

* [ ] Have you created/updated the relevant documentation page(s)?

### CODE REVIEW

**Comment by WaffleLapkin** [comment]
Also, the original issue proposes using `max(created, updated)` date, while this PR only uses `created`. Which behaviour is more desired?

**Comment by Keats** [comment]
> Also, the original issue proposes using max(created, updated) date, while this PR only uses created. Which behaviour is more desired?

This would mean that pages that were not updated would be shown at the end in your code right? `max(created, updated)` makes much more sense to me.

**Comment by WaffleLapkin** [comment]
> This would mean that pages that were not updated would be shown at the end in your code right?

I think they won't be shown at all. Anyway, yeah, `max(created, updated)` is much more reasonable. I'll fix this.

**Comment by Keats** [comment]
Looks good, can you add some tests for it?
Also what are your thoughts on https://zola.discourse.group/t/remove-lighter-heavier-and-earlier-later/767 ?

**Comment by WaffleLapkin** [comment]
> Looks good, can you add some tests for it?

Sure, can you point me to where I should add them? I'm kinda lost 😅

> Also what are your thoughts on https://zola.discourse.group/t/remove-lighter-heavier-and-earlier-later/767 ?

Hm, we only set one pair of `lighter/heavier`, `earlier/later`, … at a time, right? If so, then having only `prev/next` (or other neutral names, it's not the point) makes perfect sense to me.

**Comment by Keats** [comment]
I thought `library.rs` had tests for that but it doesn't seem that way, don't worry about it then I'll write some myself later.

**Comment by Keats** [comment]
> Hm, we only set one pair of lighter/heavier, earlier/later, … at a time, right? If so, then having only prev/next (or other neutral names, it's not the point) makes perfect sense to me.

Yep. We lose a bit of expliciteness but we only keep one name around rather than `n` for each sorting methods (and it's becoming hard to come up with them)

**Comment by WaffleLapkin** [comment]
The only question is: how to move to `prev/next` without breaking changes?

**Comment by Keats** [comment]
That would have to be a breaking change.

**Comment by WaffleLapkin** [comment]
I'm too used to people that are scared almost to death about breaking changes :D

**Pull request merged**
