### PR TITLE
Attempt to fix snap package clean build

### PR DESCRIPTION
**Pull request by brlin-tw**
The original snap recipe lacks a few build dependencies and thus errors in cleanbuild, this patch fixes it by enumerated them in `build-packages`.

Also a seemingly bug in the rust plugin is encountered and is workarounded by using a third party plugin implementation by @tismith.

NOTE: At my end the build still fails frequently due to retry count depletion when downloading crates.io libraries, which is not resolved in this patch.

Refer-to: Problem building rust based snap - snapcraft - snapcraft.io <https://forum.snapcraft.io/t/problem-building-rust-based-snap/5776>
Signed-off-by: 林博仁(Buo-ren Lin) <Buo.Ren.Lin@gmail.com>

### CODE REVIEW

**Comment by tismith** [comment]
FYI - I've raised the changes to the rust plugin as a PR back to snapcraft - see https://github.com/snapcore/snapcraft/pull/2158

**Comment by Keats** [comment]
Thanks for that, both of you!
Hopefully the plugin gets fixed soon

**Comment by musoke** [comment]
This branch builds successfully with `snapcraft cleanbuild --debug` now that the crates.io issues are resolved.  Tested with snapcraft 2.42.1 on Ubuntu 16.04.

@tismith, @sergiusens : your [changes](https://github.com/snapcore/snapcraft/pull/2170) to snapcraft's rust plugin have been merged.  Do you know how long it will be until that makes the present PR unnecessary?

**Comment by sergiusens** [comment]
We will accelerate the release a bit due to this. It usually takes a week to get all the ducks in order.

**Comment by Keats** [comment]
I've added the changes to the snapcraft.yml to the master branch and build.snapcraft fails with:

`CalledProcessError: Command '['lxc', 'exec', 'lp-xenial-amd64', '--env', 'LANG=C.UTF-8', '--env', 'SHELL=/bin/sh', '--env', 'SNAPCRAFT_LOCAL_SOURCES=1', '--env', 'SNAPCRAFT_SETUP_CORE=1', '--env', 'SNAPCRAFT_BUILD_INFO=1', '--env', 'SNAPCRAFT_IMAGE_INFO={"build_url": "https://launchpad.net/~build.snapcraft.io/+snap/0a4ad46fc9f42960f6b4e3587d6b04db-xenial/+build/281459"}', '--env', 'http_proxy=http://10.10.10.1:8222/', '--env', 'https_proxy=http://10.10.10.1:8222/', '--env', 'GIT_PROXY_COMMAND=/usr/local/bin/snap-git-proxy', '--', '/bin/sh', '-c', 'cd /build/gutenberg && linux64 snapcraft pull']' returned non-zero exit status 2`

Not entirely sure what is going on but I don't believe the issue is with the rust plugin as there is no cargo/rustc call in that command

**Comment by brlin-tw** [comment]
@Keats 
The log entries right before the CallProcessError is likely the cause.  The CallProcessError only tells that something wrong occurred when running each part's `pull` step(`snapcraft pull`).

**Comment by Keats** [comment]
The lines before the `CalledProcessError`:

```
Downloading 'rustup.sh' 100%                                                   
[17/Jul/2018:10:53:18 +0000] "CONNECT github.com:443 HTTP/1.1" 200 101123129 "-" "git/1.0 (git2-curl 0.8.1)"
Build failed
```

**Comment by Keats** [comment]
The build is running into https://bugs.launchpad.net/snapcraft/+bug/1778530 which makes Rust snaps impossible to build AFAIK.

**Comment by Keats** [comment]
Closing, the snapcraft now in master should do the right thing but there are some issues with snapcraft itself setting invalid manifest paths so the issue is upstream

**Pull request closed without merging**
