### PR TITLE
Add catppuccin highlight theme

### PR DESCRIPTION
**Pull request by SailnMobula**
The [catppuccin](https://github.com/catppuccin/catppuccin) theme is just awesome and getting more and more popular. I added the four variants `latte`, `frappe`, `macchiato`, `mocha`. I hope you love it like i do.

**IMPORTANT: Please do not create a Pull Request adding a new feature without discussing it first.**

The place to discuss new features is the forum: <https://zola.discourse.group/>
If you want to add a new feature, please open a thread there first in the feature requests section.

Sanity check:

* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/getzola/zola/pulls) for the same update/change?

## Code changes
(Delete or ignore this section for documentation changes)

* [x] Are you doing the PR on the `next` branch?

If the change is a new feature or adding to/changing an existing one:

* [x] Have you created/updated the relevant documentation page(s)?

### CODE REVIEW

**Comment by Keats** [comment]
I didn't know them but I like it! I don't think i will add more builtins themes/languages for now as we're still thinking about https://github.com/getzola/zola/issues/1787

**Comment by Jieiku** [comment]
Hey I didn't know about these either. @SailnMobula , even though no more .tmThemes are being added to Zola, you can load them in your own zola instance and then convert them to css.

From this page: https://www.getzola.org/documentation/content/syntax-highlighting/

> Zola can output a css file for a theme in the static directory using the highlight_themes_css option.

> ```toml
> highlight_themes_css = [
>   { theme = "base16-ocean-dark", filename = "syntax-theme-dark.css" },
>   { theme = "base16-ocean-light", filename = "syntax-theme-light.css" },
> ]
> ```

This is what I did for the syntax theme used in Abridge:

https://github.com/Jieiku/abridge/blob/d367a4b79c801ac0ac084032aaee388616ffe97c/sass/abridge.scss#L1306-L1505

I actually exported the tmtheme to css, and then customized it farther to be more dynamic for light/dark modes:

https://github.com/Jieiku/abridge/blob/refactor/sass/_colors-syntax.scss

Once the next version/subversion of Zola is released I plan to merge this Refactor branch for Abridge.

**Comment by SailnMobula** [comment]
Hey @Jieiku thx so much for your reply. I added the theme as .tmTheme to my project. But your approach seems a little more lightweight.

@Keats If we don't add more .tmThemes, I guess we can close this one?

**Comment by Keats** [comment]
Yes sorry. Eventually I hope i'll get enough time to work on replacing syntect and it should be easier to add themes at this point.

**Pull request closed without merging**
