### PR TITLE
Runtime syntax loading

### LINKED ISSUE #262: Runtime Syntax Loading
It'd be nice not to have to recompile gutenberg each time I update a syntax.

### PR DESCRIPTION
**Pull request by remexre**
Resolves #262.

I'm less-than-100% sure that https://github.com/remexre/gutenberg/blob/64fa890aa96a2aea351ed3ebe3257ed4b6d5dde5/components/rendering/src/markdown.rs#L104 is an appropriate course of action, but other than that, I've tested this on my own project and it works.

### CODE REVIEW

**Comment by Keats** [comment]
The code itself looks ok but I think I would like a test for it.
Also, can you run the benchmarks of the `rendering` sub-crate to see if there is any regression?

**Comment by remexre** [comment]
Okay, I'll add tests tonight.

---

9675ab190de74c1135d79681dfcefc644463cb93:
```
test bench_render_content_no_shortcode         ... bench:      58,594 ns/iter (+/- 273)
test bench_render_content_with_highlighting    ... bench:   1,073,077 ns/iter (+/- 5,828)
test bench_render_content_without_highlighting ... bench:     287,527 ns/iter (+/- 1,221)
test bench_render_shortcodes_one_present       ... bench:     217,656 ns/iter (+/- 1,169)
```

64fa890aa96a2aea351ed3ebe3257ed4b6d5dde5:
```
test bench_render_content_no_shortcode         ... bench:      61,328 ns/iter (+/- 157)
test bench_render_content_with_highlighting    ... bench:   1,074,319 ns/iter (+/- 7,664)
test bench_render_content_without_highlighting ... bench:     285,738 ns/iter (+/- 944)
test bench_render_shortcodes_one_present       ... bench:     235,043 ns/iter (+/- 788)
```

**Comment by remexre** [comment]
Ha, good thing for those tests, I didn't realize we didn't automatically chdir to the site being built.

**Comment by Keats** [comment]
Any chance you can update the docs as well? Ready to merge otherwise imo

**Comment by remexre** [comment]
Does this look good?

**Comment by Keats** [comment]
Nice, thanks!

**Pull request merged**
