### PR TITLE
Fix multi-lingual json index

### PR DESCRIPTION
**Pull request by Jieiku**
Fixes https://github.com/getzola/zola/issues/2193

Sanity check:

* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/getzola/zola/pulls) for the same update/change?

## Code changes
(Delete or ignore this section for documentation changes)

* [x] Are you doing the PR on the `next` branch?

If the change is a new feature or adding to/changing an existing one:

* [] Have you created/updated the relevant documentation page(s)? No because it is not a new feature, just a fix.

### CODE REVIEW

**Comment by Jieiku** [comment]
I am not sure why this fails the test, it worked perfectly on my linux machine, if you have any idea what I need fix/change let me know. Thanks!

**Comment by Raymi306** [comment]
If you check the details it looks like CI is failing on cargo fmt, I bet if you ran cargo fmt and committed it would pass

**Comment by Keats** [comment]
Yep, just run `cargo fmt`

**Comment by Keats** [comment]
Thanks!

**Pull request merged**
