### PR TITLE
Add blog.turbo.fish to EXAMPLES.md

### PR DESCRIPTION
**Pull request by jplatte**
Hi! Heard you were interested in more examples of Zola usage :)

### CODE REVIEW

**Comment by Keats** [comment]
Thanks!

FYI, your fonts are pretty slow to load on a bad airport wifi, ~5s during which the content is not visible :/

**Comment by jplatte** [comment]
Thanks for letting me know. I have a fallback to `sans-serif`, but I guess that doesn't apply on your system then? I'll investigate how to do improve fallback.

**Comment by jplatte** [comment]
On my system, I also see the font change from the sans serif font I have set in Firefox's preferences, to Inter during page load. And as far as I understand <https://developer.mozilla.org/en-US/docs/Web/CSS/font-family>, `sans-serif` (as well as `serif`, `monospace`, ...) should always be present. Do you have an idea what the reason may be that it isn't working for you / how I could improve things?

**Comment by Keats** [comment]
Loading fonts via `url` is blocking so it will be invisible while downloading the files afaik. Try to put a `font-display: swap` in the font-face declaration so it doesn't replace the sans-serif while loading the custom fontt

**Comment by jplatte** [comment]
Done!

**Pull request merged**
