### PR TITLE
Better minify errors

### LINKED ISSUE #1152: minfying has unhelpful error messaging and breaks on html chars in inner text
# Bug Report

## Environment

Zola version: 0.12.0 on `next` branch

## Expected Behavior
Tell us what should have happened.
I tried to build my own website with minification turned on. The website should get built and be minified. 

## Current Behavior
when I build my website with minification turned on I simply get this message: 
```
Error: Failed to truncate html at character: 15769
```
with no further information, making it impossible to tell what the problem is for the user. As I have my own version installed I did some extra digging and found the issue causing the crash for which I will open a separate issue, but this should be fixed in some way. At least I think the file currently being minified should be displayed, but ideally, a window around the error in the string currently being minified would also be shown. Displaying the entire string helps but is still very cumbersome as the files can be very large so displaying all of it is unhelpful. 

As for what is causing the exit, after doing some digging in my own installation I found out that it is because one of my pages containing the text `<<` (for nav buttons) so it seems that the inner HTML text is not properly escaped/encoded before it is minified. 

## Step to reproduce
```bash
mkdir bug && cd bug
zola init
sed -i  's/\[extra\]/minify_html = true \n [extra]/' config.toml # enable minification
echo '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"> <html lang="en"> <head> <meta http-equiv="content-type" content="text/html; charset=utf-8"> <title>Title Goes Here</title> </head> <body> <p>This is my web page</p>
        <p> <<<<<<  </p><script src="/livereload.js?port=1024&amp;mindelay=10"></script></body> </html> 
' >> templates/index.html
zola serve
```

### PR DESCRIPTION
**Pull request by areille**
**IMPORTANT: Please do not create a Pull Request adding a new feature without discussing it first.**

The place to discuss new features is the forum: <https://zola.discourse.group/>
If you want to add a new feature, please open a thread there first in the feature requests section.

Sanity check:

* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/getzola/zola/pulls) for the same update/change?

## Code changes
(Delete or ignore this section for documentation changes)

* [x] Are you doing the PR on the `next` branch?

If the change is a new feature or adding to/changing an existing one:

* [x] Have you created/updated the relevant documentation page(s)?

## Description

Closes #1152.

### CODE REVIEW

**Comment by areille** [comment]
@Keats do you want me to revert back the previous pr (#1146) in this one ?

**Comment by Keats** [comment]
It's already merged in released in 0.12, it just needs to be enabled + add back the  docs

**Comment by Keats** [comment]
Thanks!

**Comment by areille** [comment]
@Keats should I open a new PR to re-enable minify-html ? I saw that it is forced set to false in config's `mod.rs`

**Comment by Keats** [comment]
Yes please! Hopefully the big issues are fixed now

**Pull request merged**
