### PR TITLE
Fix for issue #649 - Windows auto reload not working

### PR DESCRIPTION
**Pull request by ericharding**
**IMPORTANT: Please do not create a Pull Request adding a new feature without discussing it first.**

The place to discuss new features is the forum: <https://zola.discourse.group/>
If you want to add a new feature, please open a thread there first in the feature requests section.

Sanity check:

* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

## Code changes
(Delete or ignore this section for documentation changes)

* [ ] Are you doing the PR on the `next` branch?

If the change is a new feature or adding to/changing an existing one:

* [ ] Have you created/updated the relevant documentation page(s)?

### CODE REVIEW

**Comment by Keats** [comment]
Looks like all the `serve` tests are failing?

**Comment by ericharding** [comment]
I guess canonicalize requires the files to actually exist which is kind of troublesome.  That must be why it can fail. Waiting on the conversation in the bug to go further with the PR.

**Comment by ericharding** [comment]
I removed the canonicalize calls in serve.rs and verified that the tests pass.  I also did a quick scan of the other areas that canonicalize are used and they all either compare 2 canonicalized paths or load data so they seem safe.

**Comment by ericharding** [comment]
Closing this since it's fixed by reverting the original bad change.

**Pull request closed without merging**
