### PR TITLE
cargo: run rustfmt on the codebase

### PR DESCRIPTION
**Pull request by lucab**
This applies a rustfmt pass on the whole project, in order to avoid
spurious reflows while working on unrelated changes.

---

Sanity checks:

* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/getzola/zola/pulls) for the same update/change?
* [x] Are you doing the PR on the `next` branch?
* [ ] Have you created/updated the relevant documentation page(s)?
  * LB: Not applicable

### CODE REVIEW

**Comment by Keats** [comment]
Thanks for that but it will cause merge issues with https://github.com/getzola/zola/pull/1391 which I'm planning to merge in `next` this week.

**Comment by lucab** [comment]
@Keats no worries. I was playing around the codebase to see how feasible it is to implement [backlinks](https://zola.discourse.group/t/does-zola-support-backlinks/655), and noticed a few spurious reflows. Can you maybe throw a `cargo fmt` pass on top of #1391, whenever you are done?

**Comment by Keats** [comment]
Interesting, backlinks is the feature I want to add after the i18n changes!

**Comment by lucab** [comment]
Nice. I am not yet there though, as I am slowly wading through the codebase and plumbing through primitives. I guess I can start opening PRs for those as soon as polished, though.

**Pull request closed without merging**
