### PR TITLE
Zola 1.18.0 metainfo

### PR DESCRIPTION
**Pull request by Newbytee**
I'm not sure why Ayush's 0.17.2 commit isn't in this branch, so I'm adding it too.

Sanity check:

* [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/getzola/zola/pulls) for the same update/change?

## Code changes
(Delete or ignore this section for documentation changes)

* [X] Are you doing the PR on the `next` branch?

If the change is a new feature or adding to/changing an existing one:

* [ ] Have you created/updated the relevant documentation page(s)?

### CODE REVIEW

**Review by Keats — APPROVED** [review]

**Comment by Newbytee** [comment]
@Keats Was my commit removed somehow? I don't see it in neither next nor master.

**Comment by Keats** [comment]
That's super weird, I didn't remove them but I don't see them either...?

**Comment by Newbytee** [comment]
> That's super weird, I didn't remove them but I don't see them either...?

Looking at https://github.com/getzola/zola/commit/db526689127e0b052eb69b3164a766ba61090221 it says that it does not belong to any branch in this repository, unless it was merged with a different commit hash.

**Comment by Keats** [comment]
No clue what's happening, I did merge this to next and then next into master 🤔

**Comment by Newbytee** [comment]
> No clue what's happening, I did merge this to next and then next into master 🤔

Do you want me to open a new pull request?

**Comment by Keats** [comment]
Go for it, directly on master

**Comment by Newbytee** [comment]
Opened https://github.com/getzola/zola/pull/2402.

**Pull request merged**
