### PR TITLE
feat: add base16-black-metal-bathory highlight theme

### PR DESCRIPTION
**Pull request by wantguns**
**IMPORTANT: Please do not create a Pull Request adding a new feature without discussing it first.**

The place to discuss new features is the forum: <https://zola.discourse.group/>
If you want to add a new feature, please open a thread there first in the feature requests section.

Sanity check:

* [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/getzola/zola/pulls) for the same update/change?

## Code changes
(Delete or ignore this section for documentation changes)

* [X] Are you doing the PR on the `next` branch?

If the change is a new feature or adding to/changing an existing one:

* [X] Have you created/updated the relevant documentation page(s)?

---

Add the Base16 Black Metal Bathory theme. This is a rough edit for the original theme from [@metalelf0](https://github.com/metalelf0/base16-black-metal-scheme).

### CODE REVIEW

**Comment by Keats** [comment]
Now that you can add themes/syntaxes for your own site, I don't think it makes sense to add more themes to Zola itself.

**Comment by wantguns** [comment]
> Now that you can add themes/syntaxes for your own site, I don't think it makes sense to add more themes to Zola itself.


Nice ! I wasn't aware of this.
Could you point out how to proceed with adding custom syntax themes with a prebuilt zola binary ? I have perused the documentation, but might have missed it.

**Comment by Keats** [comment]
Ah woops sorry it's not released yet.
It will be in the next version that is coming out very soon.

**Comment by wantguns** [comment]
cool, I can wait. Either way I am getting my blog's syntax highlighting theme usable directly in the next version.

**Pull request closed without merging**
