### PR TITLE
Shortcode for Streamable videos

### PR DESCRIPTION
**Pull request by williamyaoh**
Adds an embedding shortcode for Streamable videos. I wrote it for my own site and figured others might find it useful.

Takes an `id` parameter and an optional `class` parameter, just like the YouTube shortcode does.

### CODE REVIEW

**Comment by Keats** [comment]
Looks good, thanks! Can you do a PR on the `next` branch instead of master by any chance?

**Comment by williamyaoh** [comment]
Sure, no problem.

Did you want the history fixed up so that my commits only branch off `next`, or is it all right that
they still have `master` as a direct parent as well?

**Comment by williamyaoh** [comment]
Hmm, that CI failure looks to be spurious. Seems like it's caused by switching the base branch in the middle of CI. I'll close this PR and open a new one off of `next`. That'll give me the opportunity to fix up the commit history as well.

**Comment by williamyaoh** [comment]
See #80.

**Pull request closed without merging**
