### PR TITLE
Add Tomorrow theme

### PR DESCRIPTION
**Pull request by hoodie**
**IMPORTANT: Please do not create a Pull Request adding a new feature without discussing it first.**

The place to discuss new features is the forum: <https://zola.discourse.group/>
If you want to add a new feature, please open a thread there first in the feature requests section.

Sanity check:

* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/getzola/zola/pulls) for the same update/change?

## Code changes
(Delete or ignore this section for documentation changes)

* [ ] Are you doing the PR on the `next` branch?

If the change is a new feature or adding to/changing an existing one:

* [ ] Have you created/updated the relevant documentation page(s)?

### CODE REVIEW

**Comment by Keats** [comment]
You will need to rebase, switch the target to `next` and re-run the theme packing command

**Comment by hoodie** [comment]
```
error: failed to run custom build command for `sass-sys v0.4.13`
Caused by:
  process didn't exit successfully: `/target/debug/build/sass-sys-102f01a3f8967dfe/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Build error:
STDERR:cc1plus: error: unrecognized command line option '-std=c++11'cc1plus: error: unrecognized command line option '-std=c++11'
make: *** [src/ast.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [src/ast_values.o] Error 1
cc1plus: error: unrecognized command line option '-std=c++11'
make: *** [src/ast_supports.o] Error 1
cc1plus: error: unrecognized command line option '-std=c++11'
make: *** [src/ast_sel_cmp.o] Error 1
```
@Keats did you switch build containers at some point? `c++11` is unrecognized?

**Comment by Keats** [comment]
I have no idea why Travis is suddenly failing to be honest. I have a branch to switch to Azure Pipelines which I'll merge soon: https://github.com/getzola/zola/pull/750

**Comment by hoodie** [comment]
thanks :+1:

**Pull request merged**
