### PR TITLE
Docs update

### PR DESCRIPTION
**Pull request by Keats**

### CODE REVIEW

**Comment by Keats** [comment]
@piedoom I wrote some pages for deployment, any idea what content you would like to see in #202?

**Comment by piedoom** [comment]
Basic theme development practices will be useful.  I think a general guide explaining how to set up a theme to be auto-reloaded, etc. would be good.  I might write something up if I have the chance.

**Comment by Keats** [comment]
I'd be happy to take a PR on that branch for it. I'm going to work on creating the themes gallery based on the gutenberg-themes repo myself

**Comment by Keats** [comment]
Gallery generated by https://github.com/Keats/gutenberg-themes/pull/5: https://deploy-preview-219--gutenberg.netlify.com/themes/

**Pull request merged**
