### PR TITLE
Add Dracula (https://draculatheme.com) as a syntax highlighting theme

### PR DESCRIPTION
**Pull request by ryanmcgrath**
Not 100% sure if this requires being on the `next` branch, considering it's more or less an asset in the syntax highlighting pipeline. Lemme know if it's absolutely an issue and I can re-open with that I guess.

### CODE REVIEW

**Comment by Keats** [comment]
Hmm yeah it picks the commits from master as well :(
The change needs to be done in on next as it will need to be bundled on release and is easier for me to go through if all the changes are on the same branch.

Can you force push your commit?

**Comment by ryanmcgrath** [comment]
Kk, should be on my `next` branch. Lemme know if this needs anything else?

https://github.com/ryanmcgrath/zola/commit/06f1cfc881d8dbdbc46bad7773fec88d477e8dd8

**Comment by Keats** [comment]
Can you force push your branch to this PR or open a new one based on your `next` branch?

**Comment by ryanmcgrath** [comment]
Will open a new one~

**Pull request closed without merging**
