### PR TITLE
Add new flag 'no-port-append' to give the ability to remove port from base url

### PR DESCRIPTION
**Pull request by ffrizzo**
**IMPORTANT: Please do not create a Pull Request adding a new feature without discussing it first.**

The place to discuss new features is the forum: <https://zola.discourse.group/>
If you want to add a new feature, please open a thread there first in the feature requests section.

Sanity check:

* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/getzola/zola/pulls) for the same update/change?

## Code changes
(Delete or ignore this section for documentation changes)

* [x] Are you doing the PR on the `next` branch?

If the change is a new feature or adding to/changing an existing one:

* [ ] Have you created/updated the relevant documentation page(s)?

### CODE REVIEW

**Comment by ProximaB** [comment]
Sorry if I mislead you with the typo in my issue. The name of the flag should rather be ‘ appendPort’. That would be the same as in Hugo. Thanks for your PR.

**Comment by ProximaB** [comment]
Does anyone know what is the cause of this failed test? That change of the behavior is unexpected.
```
---- can_render_basic_markdown stdout ----
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Differences ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot file: components/markdown/tests/snapshots/markdown__can_render_basic_markdown.snap
Snapshot: can_render_basic_markdown
Source: components/markdown/tests/markdown.rs:27
────────────────────────────────────────────────────────────────────────────────
Expression: body
────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬───────────────────────────────────────────────────────────────────
    2     2 │ <p>Hello <em>world</em>
    3     3 │ Hello
    4     4 │ world
    5     5 │ Non rendered emoji :smile:
    6       │-<a href="image.jpg">a link</a>
          6 │+<a href="[https://www.getzola.org/test/image.jpg">a](https://www.getzola.org/test/image.jpg%22%3Ea) link</a>
    7     7 │ <img src="[https://www.getzola.org/test/image.jpg"](https://www.getzola.org/test/image.jpg%22) alt="alt text" /></p>
    8     8 │ <h1>some html</h1>
` ``

**Comment by Keats** [comment]
It should be fixed if you rebase

**Comment by ProximaB** [comment]
I thought I did test that here https://github.com/getzola/zola/pull/2007

**Comment by Keats** [comment]
Ah i might have forgotten to fix some tests. Let me check tomorrow. Nothing
to do with your PR though

**Review by ProximaB — APPROVED** [review]

**Comment by ProximaB** [comment]
@Keats Hello, any updates about that?

**Review by Keats — APPROVED** [review]

**Pull request merged**
