### PR TITLE
Check command global

### PR DESCRIPTION
**Pull request by marcusklaas**
This is take two of https://github.com/getzola/zola/pull/663. Instead of checking links at a page level, they are all gathered and then checked asynchronously.

Testing this was hard. I replaced the site level tests by a test ensuring that the right links are collected, but wasn't quite sure how to do the link check testing at a site level. Would be very grateful for any pointers in this area!

Dead link errors look this now:
```
marcusklaas@localhost ~/fully_faithful_eu> zola check
Checking site...
Failed to check the site
Error: Dead link in /home/marcusklaas/fully_faithful_eu/content/fantasy-league-data.md to ../fantasy-league-introduction: relative URL without a base
Dead link in /home/marcusklaas/fully_faithful_eu/content/pulldown-cmark.md to https://githudb.com/raphlinus/pulldown-cmark: error trying to connect
```

Doing a site check takes 2.8 seconds compared to a 7.5 second site build on zola 0.6.

---

**IMPORTANT: Please do not create a Pull Request adding a new feature without discussing it first.**

The place to discuss new features is the forum: <https://zola.discourse.group/>
If you want to add a new feature, please open a thread there first in the feature requests section.

Sanity check:

* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/getzola/zola/pulls) for the same update/change?

## Code changes
(Delete or ignore this section for documentation changes)

* [x] Are you doing the PR on the `next` branch?

If the change is a new feature or adding to/changing an existing one:

* [x] Have you created/updated the relevant documentation page(s)?

### CODE REVIEW

**Comment by marcusklaas** [comment]
Oh, and syntax highlighting is now disabled for the check command!

**Comment by Keats** [comment]
The code itself looks good!

The only thing is that I'm thinking it should be enhanced to check for the internal links (with anchors)/relative links as well. There is an upcoming change to internal links (https://github.com/getzola/zola/issues/686), I'll update this PR myself afterwards if necessary

**Comment by Keats** [comment]
I'm not sure how to test that either to be honest :/ I have seen a couple of things to change after trying it locally but no need to hold up the merge

**Comment by Keats** [comment]
The only thing is that it looks like you forgot to push a commit formatting the output to the console? It doesn't have the link and the uses `{:?}` for the result.

**Comment by marcusklaas** [comment]
You're absolutely right. I forgot to push that commit. I'll open a new PR for it.

**Pull request merged**
