### PR TITLE
fix(init):  handle already existing path

### PR DESCRIPTION
**Pull request by riginding**
This should fix the bug mentioned in #814 .

I wanted to write test for it but I had some problems testing the create_project_function.
I think to test this properly I would need to use dependency injection and pass at_least input to `ask_url` and `ask_bool` function. I wanted to ask first if this is the prefered way to do it before I start changing more of the code.

Sanity check:

* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/getzola/zola/pulls) for the same update/change?

## Code changes
(Delete or ignore this section for documentation changes)

* [x] Are you doing the PR on the `next` branch?

If the change is a new feature or adding to/changing an existing one:

* [x] Have you created/updated the relevant documentation page(s)?

### CODE REVIEW

**Comment by Keats** [comment]
The easiest way to test that would be to extract the actual creation into an another function that takes the result of the questions so it can be tested easily

**Comment by Keats** [comment]
@riginding ping

**Comment by riginding** [comment]
Sorry, for taking such a long time. I totally forgot that I opened this pull request.
I've now added the necessary tests.

**Comment by Keats** [comment]
Perfect, thanks!

**Pull request merged**
