### PR TITLE
Add llvm syntax highlighting

### LINKED ISSUE #2267: Add syntax highlighting for llvm
# Bug Report

## Environment

Zola version:

## Expected Behavior
Code blocks with `ll` should enable syntax highlighting for llvm code. For example if you view the following block on github, you will see what the highlighting is supposed to look like:

```ll
define i32 @foo() {
entry:
  br i1 true, label %if.then, label %if.else
if.then:
  ret i32 10
if.else:
  ret i32 12
}
```

## Current Behavior
There is no syntax higlighting when `ll` is used.

### PR DESCRIPTION
**Pull request by michaelmaitland**
Closes #2267

### CODE REVIEW

**Comment by Keats** [comment]
Thanks for the PR. I'm not going to add more built in syntaxes for now while we're looking at alternatives for highlighters.

**Comment by michaelmaitland** [comment]
That’s unfortunate. Do you have any reason why we can’t add it today and remove it when we have an alternative syntax highlighting solution implemented? By that logic let’s remove all syntax highlighting for all languages since we’re looking into rehauling syntax highlighting that might get implemented one day.

**Comment by Keats** [comment]
It's trivial to add syntaxes as an end user.

> By that logic let’s remove all syntax highlighting for all languages since we’re looking into rehauling syntax highlighting that might get implemented one day.

Let's not add more when the future is uncertain, no reason to break more stuff people rely on.

**Comment by michaelmaitland** [comment]
> It's trivial to add syntaxes as an end user

can you link to this? I don’t know how to do this without maintaining my own downstream zola repo and build. 

> no reason to break more stuff people rely on

is there a reason why you think this change would break anything? It looks like zola has a clear track record of adding new languages without introducing any new problems. Why would this be any different?

**Comment by Keats** [comment]
In https://www.getzola.org/documentation/content/syntax-highlighting/  search for `extra_syntaxes_and_themes`

> Why would this be any different?

We're looking at tree-sitter in https://github.com/getzola/zola/issues/1787 which supports fewer languages than Sublime, or sometimes they support it but the parser is 100MB and I'm not going to add it to Zola because it's too big.

**Comment by michaelmaitland** [comment]
#1787 has been open for 1,5 years and the work you need from tree-sitter does not look like it is actively being worked on nor is there a timeline for its completion. 

The [link](https://www.getzola.org/documentation/content/syntax-highlighting/) you sent me to says to make a PR to add a syntax. 

> If the language you want to highlight is not on this list, please follow our [contribution guidelines](https://github.com/getzola/zola/blob/master/CONTRIBUTING.md) to add support for a new language.

It’s a small syntax I’m adding and there’s a very low chance it’s going to break anything based on the fact that we’re following an established method of adding syntax’s that hasn’t caused problems in the last. 

I’m asking for you to make the change in the interim while you figure out tree-sitter, based on the instructions in the documentation you linked me of how to add a new syntax.

**Comment by Keats** [comment]
I've just updated the docs.

**Pull request closed without merging**
