### PR TITLE
Superfluous `mut` & clippy

### PR DESCRIPTION
**Pull request by virtualritz**
Kept seeing this `mut` babble whenever I ran an update on my `zola` install so ... 

While at it, also made `clippy` happy.

### CODE REVIEW

**Comment by Keats** [comment]
Can you do the PR on the next branch?

**Comment by phocks** [comment]
I was about to do a PR to remove the mut on p as well. It's already here. Nice.

**Comment by Keats** [comment]
It's not done on the right branch though

**Comment by Keats** [comment]
I've cherry picked the commit, thanks!

**Pull request closed without merging**
