### PR TITLE
Let toc is visable through Page & Section variables in templates

### PR DESCRIPTION
**Pull request by nottxy**
Sanity check:

* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/getzola/zola/pulls) for the same update/change?

Yes

## Code changes

* [x] Are you doing the PR on the `next` branch?

Yes

If the change is a new feature or adding to/changing an existing one:
* [x] Have you created/updated the relevant documentation page(s)?

Yes

### CODE REVIEW

**Comment by Keats** [comment]
Is that specifically for https://github.com/getzola/zola/issues/694 or did you need that yourself?

The PR itself looks good, although it might be worth it removing the current `toc` variable from page/section to avoid serializing it twice.

**Comment by nottxy** [comment]
Yes, kind of some case like #694 .

It is better that the `toc` could be removed from page & section, but there would be a break change.

**Comment by Keats** [comment]
> It is better that the toc could be removed from page & section, but there would be a break change.

That's fine, next version is planned to have breaking changes.

**Comment by Keats** [comment]
Thanks!

**Pull request merged**
