### PR TITLE
Markdown next

### LINKED ISSUE #165: Shortcode names and arguements.
It appears as though shortcode file names cannot have an underscore in them and that the value that argument values cannot contain special characters.

To reproduce the filename issue:
- create shortcode, `./templates/shortcodes/contact_info.html`.
```
{{ label }}
{{ info }}
```
- use shortcode
```
{{ contact_info(label="this is a label", info="this is the info") }}
```

To reproduce the argument issue:
- create shortcode, `./templates/shortcodes/contact.html`.
```
{{ label }}
{{ info }}
```
- use shortcode
```
{{ contact(label="this is a label", info="this [is the] info") }}
```
This is exacerbated because it appears the dev server will fall back to a previous state when it cannot build correctly...and then sometimes gets stuck and needs to be manually restarted.

### PR DESCRIPTION
**Pull request by Keats**
Closes #165 #298 #297 #270 #249 #160

### CODE REVIEW

**Comment by Keats** [comment]
@jturner314 @RadicalZephyr @reillysiemens @cldershem @clarcharr @NuLL3rr0r @piedoom 

I believe this solves all current issues/missing features with markdown rendering/shortcodes if any of you want to give it a try

**Comment by clarfonthey** [comment]
I'll try this out later today or tomorrow.

**Comment by piedoom** [comment]
This is some awesome work!  Thanks.

**Comment by Keats** [comment]
(merging into next as this affects other PRs but i'll still take feedback)

**Pull request merged**
