### PR TITLE
remove square brackets

### LINKED ISSUE #2640: `bottom_footnotes` config adds unwanted square brackets to footnote references
Hello.

The square brackets around footnotes references applied when `bottom_footnotes` config is set is not documented anywhere, and honestly, looks ugly. They should either be removed or made as a config option.

The removal is a tiny change I made in my fork here [here](https://github.com/getzola/zola/commit/460e61a4b4bd7dc405459a7094cfb896535ca074). I did not want to create a pull request, however, without clearing that it is ok to do so.

The additional config option would be a bit more involved: Upgrade the `bottom_footnotes` config to an enum with `Default`, `Bottom`, `Github-style` etc.

### PR DESCRIPTION
**Pull request by asibahi**
closes #2640

redo of #2644

### CODE REVIEW

**Comment by Keats** [comment]
Looks like we need to re-run the insta tests. Let me know if you need help with it or I can do it

**Comment by asibahi** [comment]
Unfortunately CI and CI tests are voodoo to me. Why would the tests fail?

**Comment by Keats** [comment]
We have integration tests testing the output of markdown rendering and they need to be updated. I'll handle it when I have a bit of time

**Comment by Keats** [comment]
Pushed it to next but i fucked up the merge somehow so GH didn't recognise it :/

**Pull request closed without merging**
