### PR TITLE
Make themes more flexible

### PR DESCRIPTION
**Pull request by southerntofu**
* [x] Are you doing the PR on the `next` branch?
* [ ] Have you created/updated the relevant documentation page(s)?
* [x] The change is fully backwards-compatible 

Fix for both #324 and #361. I open this PR to bring more attention so everyone can test and see if it makes them happy.

Following remarks [here](https://github.com/getzola/zola/issues/324#issuecomment-618257210), i made sure this patch was fully backwards-compatible by copying the template's theme (inside tera) to  "THEME/templates/index.html" in all cases, where THEME is the theme name.

In addition, I propose to copy all theme templates to "theme/templates/" where "theme" is a literal. This would allow site templates to extend the theme's template regardless of the theme name, so that  you can swap themes seemlessly as long as they implement the same blocks in the base template. Would this be ok?

Waiting for feedback before i edit the docs

### CODE REVIEW

**Comment by southerntofu** [comment]
done. the section is formatted properly and tests pass

**Comment by Keats** [comment]
It looks like it works while being much simple?! Can you add tests for shortcodes and an actual `include`?

**Comment by Keats** [comment]
ping @southerntofu

**Comment by Keats** [comment]
I didn't mean to close all the PRs by deleting the branch :(

**Comment by southerntofu** [comment]
> Can you add tests for shortcodes and an actual include?

done. i also updated the docs

> In addition, I propose to copy all theme templates to "theme/templates/" where "theme" is a literal. This would allow site templates to extend the theme's template regardless of the theme name, so that you can swap themes seemlessly as long as they implement the same blocks in the base template. Would this be ok?

^ Would this change be welcome?

**Comment by Keats** [comment]
> This would allow site templates to extend the theme's template regardless of the theme name, so that you can swap themes seemlessly as long as they implement the same blocks in the base template.

I don't think it's common enough. And right now you can easily tests multiple themes and pick the one you prefer, which was the original intent.

**Comment by Keats** [comment]
It looks good to me; anything else you want to add to the PR?

**Pull request merged**
