### PR TITLE
Move sublime into config module

### PR DESCRIPTION
**Pull request by bemyak**
This is maybe a bit of controversial change, but I stumbled upon inability to build my crate (which depends on some parts of Zola) using Nix. The problem is that Nix builds every crate in an isolated environment, but since the `config` component depends on sublime files outside its crate root, the build fails.

I discussed the issue with a person who maintains the rust harness for Nix, and he suggested fixing it in Zola: https://github.com/ipetkov/crane/discussions/666#discussioncomment-10079661
There's a bit more info attached there.

Hope you will consider these changes :blush: 
It would also make publishing Zola's subcrates to crates.io a bit more feasible.

---
Sanity check:

* [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/getzola/zola/pulls) for the same update/change?
* [X] Are you doing the PR on the `next` branch?

### CODE REVIEW

**Comment by Keats** [comment]
I think it's fine? I can't think of issues caused by that.

**Comment by bemyak** [comment]
I don't think there are any issues caused by this change, it's more like a matter of aesthetics :slightly_smiling_face: 

If you don't object, maybe let's get it merged?

**Comment by Keats** [comment]
Yep sorry forgot about it

**Comment by bemyak** [comment]
Thank you! 🙏

**Pull request merged**
