### PR TITLE
WIP: Pages "inherit" assets from a section they colocate with (#877)

### PR DESCRIPTION
**Pull request by southerntofu**
The problem described in #877 is solved by this patch though in a very unoptimal way because all assets shared between pages in a section will be copied over to all pages output folders. This is because declaring the files as page assets will trigger their copy when rendering the page. I don't see a more elegant way to solve it (yet). Any ideas?

### CODE REVIEW

**Comment by Keats** [comment]
How about having a flag on a page whether it's a page with colocated assets or not. If there is, do like right now but if there isn't, in the markdown renderer (L125 of markdown.rs) make a link from the parent instead.

**Comment by southerntofu** [comment]
> How about having a flag on a page whether it's a page with colocated assets or not

Markdown links would work but then `page.assets` would be empty for those pages which is not expected behavior (eg. if a template lists a page's related assets). I'll try to dig deeper into how asset management works.

**Comment by Keats** [comment]
I think that's fine, page.assets is only for colocated assets and if the asset is in the directory it isn't colocated with anything.

**Comment by southerntofu** [comment]
The latest commit only copies assets once, but has them declared in the associated section/pages as expected. Relative links from Markdown are fixed on the go, and assets still returns paths from the content folder, which means we can't use page.assets in templates as relative URLs, but have to concatenate with the base_url (as was already the case).

This commit was tested with the following `page.html`:

```
{% for i in page.assets %}
{% if i is ending_with(".png") %}
<img src="{{ resize_image(path=i, width=400, op="fit_width") }}">
<img src="{{ config.base_url }}/{{ i }}">
{% endif %}
{% endfor %}
```

Waiting for feedback before i add some tests.

Not very interesting but worth mentioning for #687: for a "page in page" where the "parent" page has a different path/slug, the link produced in the "child" page will be incorrect.

**Comment by Keats** [comment]
I still don't know whether to support that or not...

**Pull request closed without merging**
