### PR TITLE
Minify embedded css and js

### PR DESCRIPTION
**Pull request by JeremyBarbosa**
**IMPORTANT: Please do not create a Pull Request adding a new feature without discussing it first.**

The place to discuss new features is the forum: <https://zola.discourse.group/>
If you want to add a new feature, please open a thread there first in the feature requests section.

Sanity check:

* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/getzola/zola/pulls) for the same update/change?

## Code changes
(Delete or ignore this section for documentation changes)

* [x] Are you doing the PR on the `next` branch?

If the change is a new feature or adding to/changing an existing one:

* [x] Have you created/updated the relevant documentation page(s)?

## Notes
A relatively small fix for https://github.com/getzola/zola/issues/1765. The most notable change is an added dependency on `js-esbuild` and thereby the Go compiler as mentioned in the documentation for `minify-html` in order to minify CSS and JS:
https://github.com/wilsonzlin/minify-html#get-1

### CODE REVIEW

**Comment by mwcz** [comment]
I think this is a great feature, and I love esbuild (which I see minify-html binds to).  One potential issue is that this PR introduces the go compiler as a dependency for building Zola.  From [minify-html](https://crates.io/crates/minify-html):

> Building with the `js-esbuild` feature requires the Go compiler to be installed as well, to build the [JS and CSS minifier](https://github.com/wilsonzlin/esbuild-rs).

Building zola without a go compiler:

```
$ cargo build
   Compiling esbuild-rs v0.13.8
   Compiling libc v0.2.116
   Compiling maybe-uninit v2.0.0
   Compiling encoding v0.2.33
   Compiling crossbeam-utils v0.7.2
   Compiling memoffset v0.5.6
   Compiling syn v1.0.86
error: failed to run custom build command for `esbuild-rs v0.13.8`

Caused by:
  process didn't exit successfully: `/home/user/projects/rh/zola/master/target/debug/build/esbuild-rs-b3a6a716bc734fb5/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'compile Go library: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/esbuild-rs-0.13.8/build.rs:27:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by Keats** [comment]
Yeah, requiring a Go compiler is definitely a no-go there.

**Comment by JeremyBarbosa** [comment]
Yup that makes complete sense! Sorry I already had go installed so I glossed over how big of a problem that would be. Closing.

**Comment by mwcz** [comment]
/me ponders compiling esbuild to wasm and shipping that with Zola 🤔😁

**Comment by Keats** [comment]
I think it would be easier to see if swc has something for that.

**Pull request closed without merging**
