### PR TITLE
Expand documentation about sorting pages

### PR DESCRIPTION
**Pull request by codesections**
This pull request expands the documentation regarding sorting, as discussed in issue #338.

The biggest change is to pull the main discussion of sorting out of the `content/section` page and into its own page in the `templates` section.  My logic for this change is that sorting order really only comes up when iterating over pages/sections in a template.  I left enough detail in the `content/section` page for users to know how to set the `sort_by` variable and referred them to the new `templates/iterating and sorting` page for details.

Happy to discuss or make any changes you think would be appropriate.

### CODE REVIEW

**Comment by Keats** [comment]
The text is good but I think it should be in `content` rather than `templates` imo, in the `sections.md` file like it was

**Comment by codesections** [comment]
Let me explain why I moved it and then, if you still disagree, I'm happy to move it back to `sections.md`.

If you're writing content without writing templates (e.g., using someone else's themes without any files in your `templates/` directory), then you don't need to know about `reverse` filters, `page.next`/`page.previous`, or any of the rest.  After all, you *can't* call `page.next` from inside a content file—only from inside a template.  *All* the content writer needs to know is that the `_index.md` file can have set a `sort_by` variable to `date`, `order`, or `weight`.  And my view is that the `content` section of the docs should be limited (as much as possible) to what the content creator needs to know.  

The user who wants to make their own templates, on the other hand, needs to know all about the ways `order` and `weight` interact with `reverse` and how that impacts `page.next`.  I think that sort of advanced info is best kept specific to creating templates, which is the only place where it really comes up.

But, if you disagree, I'll move it back.

**Comment by Keats** [comment]
> And my view is that the content section of the docs should be limited (as much as possible) to what the content creator needs to know

I agree on that but I think the different sort types are part of the content since that's where we explain all the options in the front-matter. I would find it weird to have a couple of options explained in a completely different part of the documentation. We can always move it back to templates later if other people prefer it

**Comment by codesections** [comment]
Ok, moved it back.

**Pull request merged**
