### PR TITLE
Update dockerfile to remove hardcoded version number

### PR DESCRIPTION
**Pull request by nrjais**
This updates the dockerfile so new images can be created when a release is made(issue #938).

### CODE REVIEW

**Comment by Keats** [comment]
The weird part is that the Dockerfile did work for 0.8 but not 0.9...
Would it make sense to do a multi-stage Dockerfile so the end image doesn't have rustup/cargo installed?

**Comment by nrjais** [comment]
It is already a multi stage Dockerfile

**Comment by Keats** [comment]
🤦‍♂ I should have expanded the bottom

**Comment by nrjais** [comment]
> The weird part is that the Dockerfile did work for 0.8 but not 0.9...

Which Dockerfile are you talking about? I have tested the changes with master branch which is working fine.

**Comment by Keats** [comment]
> Which Dockerfile are you talking about? I have tested the changes with master branch which is working fine.

On the Docker hub. The automatic build worked for 0.8.0 and failed for 0.9.0
I think the issue is that I didn't set DOCKER_TAG to be equal to the git tag in the automated build.

Screenshot 2020-01-29 at 09 21 58

So it's download the file at `latest` which doesn't exist.

**Comment by nrjais** [comment]
I have mentioned the configuration in the issue #938 which can be used to automate release based on the tags.
You can also add a step to azure pipelines to build and push the image to docker hub that way there won't be any need to maintain the configuration on docker hub.
Let me know if you need anything else.

**Comment by Keats** [comment]
Which approach would you recommend? The current Dockerfile fails even after fixing the docker tag value

```
 Downloading https://files.pythonhosted.org/packages/fb/40/f3adb7cf24a8012813c5edb20329eb22d5d8e2a0ecf73d21d6b85865da11/MarkupSafe-1.1.1-cp27-cp27mu-manylinux1_x86_64.whl
Building wheels for collected packages: dockerize
Running setup.py bdist_wheel for dockerize: started
Running setup.py bdist_wheel for dockerize: finished with status 'error'
Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-q1K_Rw/dockerize/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-AETbdm --python-tag cp27:
usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
or: -c --help [cmd1 cmd2 ...]
or: -c --help-commands
or: -c cmd --help
error: invalid command 'bdist_wheel'
```
so I'm not attached to one or the other

**Comment by nrjais** [comment]
I am able to build it when making a new release as previous releases will have the old dockerfile which only works for v0.8.0 release. After configuring the autobuild with regex on tag new releases with the this dockerfile file should work.

**Comment by Keats** [comment]
Thanks!

**Pull request merged**
