### PR TITLE
Support anchors without quotes in link checker

### PR DESCRIPTION
**Pull request by siiptuo**
Sanity check:

* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/getzola/zola/pulls) for the same update/change?

## Code changes

* [x] Are you doing the PR on the `next` branch?

If the change is a new feature or adding to/changing an existing one:

* [ ] Have you created/updated the relevant documentation page(s)?

### CODE REVIEW

**Comment by Keats** [comment]
Is that even valid HTML? :o

**Comment by siiptuo** [comment]
I'm pretty sure it's valid because [HTML Living Standard](https://html.spec.whatwg.org/) itself doesn't use quotes.

**Comment by Keats** [comment]
> I'm pretty sure it's valid because HTML Living Standard itself doesn't use quotes.

It does? I see all the ids between double quotes in the console

**Comment by siiptuo** [comment]
Here's the relevant part of the specification: https://html.spec.whatwg.org/#unquoted

> > I'm pretty sure it's valid because HTML Living Standard itself doesn't use quotes.
> 
> It does? I see all the ids between double quotes in the console

I mean quotes are not used in the actual HTML source of the specification. Browser developer tools usually display double quotes when inspecting the DOM.

**Comment by Keats** [comment]
Thanks!

**Pull request merged**
