### PR TITLE
Add example site

### PR DESCRIPTION
**Pull request by trevordmiller**
- Add example site
- Update formatting to work with the new example which is now the longest string

Sanity check:

* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/getzola/zola/pulls)?

### CODE REVIEW

**Comment by Keats** [comment]
Can you remove the .swp and not change the other lines? I'm guessing vim is converting some space to tab or something

**Comment by trevordmiller** [comment]
Yeah no problem on removing the .swp (my bad). The other lines were changed with the width of the table - since the new example is now the longest "cell".

**Comment by trevordmiller** [comment]
@Keats Ok I fixed the .swp. I could remove the diffs from the other lines, but then the table will no longer be aligned

```
# Before
:----------------------------------------------------:|
# After
:--------------------------------------------------------:|
```

**Comment by Keats** [comment]
Tthanks!

**Pull request merged**
