### PR TITLE
Add path annotation for codeblock

### PR DESCRIPTION
**Pull request by izissise**
https://zola.discourse.group/t/allow-to-specify-path-associated-with-a-codeblock/2253

Sanity check:

* [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/getzola/zola/pulls) for the same update/change?

## Code changes
(Delete or ignore this section for documentation changes)

* [X] Are you doing the PR on the `next` branch?

If the change is a new feature or adding to/changing an existing one:

* [X] Have you created/updated the relevant documentation page(s)?

### CODE REVIEW

**Comment by Keats** [comment]
What's the main usage for it? Is it be displayed or retrieve by the frontend?

**Comment by izissise** [comment]
For now I use it like so:
```
pre code[data-path]:after {
  border-radius: 0 0 0.25rem 0.25rem;
  font-size: 12px;
  letter-spacing: .025rem;
  padding: .1rem .5rem;
  position: absolute;
  left: 5.5rem;
  margin-top: 0;
  text-align: right;
  top: 0;
  content: attr(data-path);
  background: lightgrey;
  color: green;
  visibility: visible;
}
```

I find useful to have the required file path associated with the code block when blogging about specific tool configuration. Some tools expect configuration at pre determined paths

**Comment by Keats** [comment]
I agree it's nice, I'm just wondering if it doubles as the code sample name as well potentially?

**Comment by Keats** [comment]
Ah can you rebase the PR? It looks like it's got some unrelated stuff due to the last release

**Comment by izissise** [comment]
Yes I agree it could be the name. I can change `path` to `name` as you prefer

**Comment by izissise** [comment]
I rebased the branch

**Comment by Keats** [comment]
Let's call it name, this way it can be used for more stuff.

**Comment by izissise** [comment]
Should be good :)

**Review by Keats — APPROVED** [review]

**Comment by piegamesde** [comment]
While toying around with this feature for #2867, trying to come up with some good CSS making use of this feature, I came across a fundamental limitation: Because the way the information is put into the DOM, it can only be made visible in CSS via pseudo-elements like `::before`. However, these can never be selected by the user.

This is very unfortunate, because in technical writing, being able to copy the file name is as important as being able to copy the code. Could be maybe revise the HTML generation for this to produce DOM elements instead?

**Pull request merged**
